# Disabling sudo lets us use the "new" Travis infrastructure
sudo: false

language: android

script: ./gradlew check --continue

android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository
